name: lms-deployment

on:
  workflow_dispatch:

jobs:
  notifications:
    runs-on: ubuntu-latest
    steps:
      - name: send notifications
        uses: slackapi/slack-github-action@v2.1.1
        with:
        webhook: ${{ secret.SLACK_WENJOOK_URL }}
        webhook-type: incoming-webhook
        payload: |
          {
            "channel": "project-7",
            "text": "LMS Production Deployment Started, Required Approval to Continue..."
          }

    approval:
      needs:
      run-on: ubuntu-latest
      environment:
        name: production-1
      steps:
        - name: approval configuration
          run: echo "approval given to deploy into production"

    database:
      needs: approval
      runs-on: ubuntu-latest
      steps:
        - name: create db
          run: echo "database container created"
